version: 2

sphinx:
  configuration: Docs/conf.py

formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: Docs/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - all
