
base = /media/setepenre/Games/
project = cartpole/Cartpole.uproject
engine = UnrealEngine/Engine/Binaries/Linux/UE4Editor

train:
	python cartpole/train.py --project $(base)/$(project) --exec $(base)/$(engine)
