name: tests

on: [push]
jobs:
  cooking:
    runs-on: ubuntu-latest
    container:
      # Slim version is 20 Go
      image: ghcr.io/epicgames/unreal-engine:dev-slim-4.27
      credentials:
        username: ${{ github.actor }}
        # Setting > Developper Setting > Personnal Access Token
        password: ${{ secrets.CONTAINER_REGISTRY_PAT }}

    steps:
      - name: Update Git
        run: |
          sudo add-apt-repository ppa:git-core/ppa -y
          sudo apt-get update
          sudo apt-get install git -y
          git --version

      - uses: actions/checkout@v2

      - name: Cook
        run: |
          # Paths need to be absolute
          # or they are considered relative to the Engine
          export PROJECT="$(pwd)/Cartpole.uproject"
          export COOKED="$(pwd)/Cooked"
          export LOGS="$(pwd)/Saved/UAT"

          mkdir -p $LOGS
          mkdir -p $COOKED

          uebp_LogFolder=$LOGS /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh \
            BuildCookRun                                           \
            -unattended                                            \
            -utf8output                                            \
            -platform=Linux                                        \
            -clientconfig=Shipping                                 \
            -serverconfig=Shipping                                 \
            -project=$PROJECT                    \
            -noP4 -nodebuginfo -allmaps                            \
            -cook -build -stage -prereqs -pak -archive             \
            -archivedirectory=$COOKED

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: cooked-cartpole-linux
          path: Cooked/*
